### ISSUE TITLE
Could you let me know who you are?

### ISSUE THREAD

**Issue by jankincl** [jis0324/zilculator-api#6]
Could you let me know who you are?
maybe, are you an owner of zilculator.com?

_Originally posted by @jis0324 in https://github.com/jis0324/zilculator-api/issues/5#issuecomment-1152680208_

Yes, I am the owner of the code. You even mentioned my name in the repo description.

**Comment by jis0324** [comment]
I am a dev and performed one part of this project,
Actually, I also knew he is not the owner of the site, he just was a recruiter.
But since I did not get the payment from him, I just wanted to share his source.
maybe, You might blame me, but I don't care because I blame him instead.
